import 'package:kubb_domain/src/tournament/pairing/buchholz.dart';

/// Golden dataset — SM Einzel 2026 (Schoch/Swiss, kubb.live), derived 1:1 from
/// docs/examples/sm-einzel-2026.md: 73 players, 8 rounds, 288 matches + 8 byes.
///
/// The expected Buchholz vectors follow schoch-swiss-pairing-buchholz-spec.md
/// §5: per opponent G, total(G) minus what G scored head-to-head against P; a
/// bye contributes nothing on the bye player's side, but the +16 bye credit
/// stays in that player's total and so feeds every real opponent's Buchholz.
/// Points are the own-score sum over all rounds with a Schoch bye worth 16
/// (spec §4). kubb.live is the empirical source of truth here; these vectors
/// match it 73/73 for both points and Buchholz.
/// 288 real matches of SM Einzel 2026, parsed verbatim from
/// docs/examples/sm-einzel-2026.md (`SpielerA,SpielerB,PunkteA,PunkteB`).
/// Player names are kubb.live nicknames (pseudonyms), taken 1:1.
const smEinzel2026Matches = <MatchResult>[
  // Runde 1
  MatchResult(participantA: 'Beni the Gun', participantB: "N'Ivo", pointsA: 16, pointsB: 5, roundNumber: 1),
  MatchResult(participantA: 'Ikarus', participantB: 'Jim Panse', pointsA: 16, pointsB: 8, roundNumber: 1),
  MatchResult(participantA: 'Hafenkneipenleiter', participantB: 'Kubbernikus', pointsA: 16, pointsB: 4, roundNumber: 1),
  MatchResult(participantA: 'Buschi', participantB: 'Pitsch Loco', pointsA: 16, pointsB: 3, roundNumber: 1),
  MatchResult(participantA: 'Chopstick', participantB: 'Benji', pointsA: 16, pointsB: 6, roundNumber: 1),
  MatchResult(participantA: 'Boskoop', participantB: 'Snoerkel', pointsA: 16, pointsB: 5, roundNumber: 1),
  MatchResult(participantA: 'Sparringspartner', participantB: 'Stüfi', pointsA: 16, pointsB: 5, roundNumber: 1),
  MatchResult(participantA: 'Magic Marco', participantB: 'Cöbi', pointsA: 16, pointsB: 2, roundNumber: 1),
  MatchResult(participantA: 'Bradley', participantB: 'mésé', pointsA: 7, pointsB: 16, roundNumber: 1),
  MatchResult(participantA: 'Voegi18', participantB: 'Diese', pointsA: 16, pointsB: 5, roundNumber: 1),
  MatchResult(participantA: 'Croci-Torti', participantB: 'Panda', pointsA: 9, pointsB: 9, roundNumber: 1),
  MatchResult(participantA: 'Gravensteiner', participantB: 'Tom Kreuzfahrt', pointsA: 16, pointsB: 5, roundNumber: 1),
  MatchResult(participantA: 'Hakubba Matata', participantB: 'ND', pointsA: 16, pointsB: 6, roundNumber: 1),
  MatchResult(participantA: 'Pabst', participantB: 'RougeOMat', pointsA: 11, pointsB: 12, roundNumber: 1),
  MatchResult(participantA: 'joker', participantB: 'Galbi', pointsA: 16, pointsB: 6, roundNumber: 1),
  MatchResult(participantA: 'Ozempic', participantB: 'Chlötzli Chrigi', pointsA: 16, pointsB: 4, roundNumber: 1),
  MatchResult(participantA: 'Kubb-Elch', participantB: 'Börny', pointsA: 16, pointsB: 0, roundNumber: 1),
  MatchResult(participantA: 'Backpacker', participantB: 'Louis de Kubbi', pointsA: 16, pointsB: 7, roundNumber: 1),
  MatchResult(participantA: 'Cheesu', participantB: 'Stibe', pointsA: 16, pointsB: 4, roundNumber: 1),
  MatchResult(participantA: 'Mandoo', participantB: 'Schibu', pointsA: 16, pointsB: 2, roundNumber: 1),
  MatchResult(participantA: 'Wadli', participantB: 'Kubbacca', pointsA: 16, pointsB: 1, roundNumber: 1),
  MatchResult(participantA: 'Driiibiii', participantB: 'Eytinu', pointsA: 16, pointsB: 2, roundNumber: 1),
  MatchResult(participantA: 'Düpiträn', participantB: 'Clint Eastwood', pointsA: 1, pointsB: 16, roundNumber: 1),
  MatchResult(participantA: 'Fül', participantB: 'KUBBO', pointsA: 13, pointsB: 7, roundNumber: 1),
  MatchResult(participantA: 'Rolli', participantB: 'Pischi', pointsA: 16, pointsB: 7, roundNumber: 1),
  MatchResult(participantA: 'Lúcio', participantB: 'Balu der Bär', pointsA: 10, pointsB: 12, roundNumber: 1),
  MatchResult(participantA: 'Giansibar', participantB: 'Ju', pointsA: 4, pointsB: 16, roundNumber: 1),
  MatchResult(participantA: 'Sarys', participantB: 'Chibber', pointsA: 7, pointsB: 16, roundNumber: 1),
  MatchResult(participantA: 'The Sheep', participantB: 'Meff', pointsA: 16, pointsB: 4, roundNumber: 1),
  MatchResult(participantA: 'Deadeye Dye', participantB: 'Pluseis', pointsA: 16, pointsB: 2, roundNumber: 1),
  MatchResult(participantA: 'Coco Vin', participantB: 'All in', pointsA: 16, pointsB: 5, roundNumber: 1),
  MatchResult(participantA: 'Gourmet', participantB: 'Adi M', pointsA: 3, pointsB: 16, roundNumber: 1),
  MatchResult(participantA: 'simuck', participantB: 'LaMartina', pointsA: 13, pointsB: 8, roundNumber: 1),
  MatchResult(participantA: 'Laura', participantB: 'Cheneraaal', pointsA: 3, pointsB: 16, roundNumber: 1),
  MatchResult(participantA: 'Sie', participantB: 'Mariiins', pointsA: 8, pointsB: 13, roundNumber: 1),
  MatchResult(participantA: 'Persuadé', participantB: 'Borgonuovo', pointsA: 5, pointsB: 11, roundNumber: 1),
  // Runde 2
  MatchResult(participantA: 'Beni the Gun', participantB: 'Cheesu', pointsA: 13, pointsB: 6, roundNumber: 2),
  MatchResult(participantA: 'Ikarus', participantB: 'Mandoo', pointsA: 12, pointsB: 13, roundNumber: 2),
  MatchResult(participantA: 'Hafenkneipenleiter', participantB: 'Wadli', pointsA: 16, pointsB: 4, roundNumber: 2),
  MatchResult(participantA: 'Buschi', participantB: 'Driiibiii', pointsA: 16, pointsB: 4, roundNumber: 2),
  MatchResult(participantA: 'Chopstick', participantB: 'Rolli', pointsA: 12, pointsB: 11, roundNumber: 2),
  MatchResult(participantA: 'Boskoop', participantB: 'The Sheep', pointsA: 16, pointsB: 4, roundNumber: 2),
  MatchResult(participantA: 'Sparringspartner', participantB: 'Deadeye Dye', pointsA: 16, pointsB: 5, roundNumber: 2),
  MatchResult(participantA: 'Magic Marco', participantB: 'Coco Vin', pointsA: 3, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'Voegi18', participantB: 'Die Nase', pointsA: 16, pointsB: 2, roundNumber: 2),
  MatchResult(participantA: 'Gravensteiner', participantB: 'mésé', pointsA: 9, pointsB: 11, roundNumber: 2),
  MatchResult(participantA: 'Hakubba Matata', participantB: 'Clint Eastwood', pointsA: 11, pointsB: 12, roundNumber: 2),
  MatchResult(participantA: 'joker', participantB: 'Ju', pointsA: 6, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'Ozempic', participantB: 'Chibber', pointsA: 16, pointsB: 2, roundNumber: 2),
  MatchResult(participantA: 'Kubb-Elch', participantB: 'Cheneraaal', pointsA: 10, pointsB: 11, roundNumber: 2),
  MatchResult(participantA: 'Backpacker', participantB: 'Adi M', pointsA: 9, pointsB: 11, roundNumber: 2),
  MatchResult(participantA: 'Fül', participantB: 'Mariiins', pointsA: 8, pointsB: 4, roundNumber: 2),
  MatchResult(participantA: 'simuck', participantB: 'RougeOMat', pointsA: 12, pointsB: 9, roundNumber: 2),
  MatchResult(participantA: 'Balu der Bär', participantB: 'Pabst', pointsA: 10, pointsB: 9, roundNumber: 2),
  MatchResult(participantA: 'Borgonuovo', participantB: 'Croci-Torti', pointsA: 7, pointsB: 12, roundNumber: 2),
  MatchResult(participantA: 'Lúcio', participantB: 'Panda', pointsA: 9, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'Sie', participantB: 'LaMartina', pointsA: 6, pointsB: 10, roundNumber: 2),
  MatchResult(participantA: 'Jim Panse', participantB: 'Bradley', pointsA: 10, pointsB: 13, roundNumber: 2),
  MatchResult(participantA: 'Sarys', participantB: 'KUBBO', pointsA: 3, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'Louis de Kubbi', participantB: 'Pischi', pointsA: 10, pointsB: 6, roundNumber: 2),
  MatchResult(participantA: 'Benji', participantB: 'Galbi', pointsA: 5, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'ND', participantB: 'Persuadé', pointsA: 9, pointsB: 7, roundNumber: 2),
  MatchResult(participantA: "N'Ivo", participantB: 'Diese', pointsA: 16, pointsB: 4, roundNumber: 2),
  MatchResult(participantA: 'Snoerkel', participantB: 'Tom Kreuzfahrt', pointsA: 11, pointsB: 5, roundNumber: 2),
  MatchResult(participantA: 'Stüfi', participantB: 'All in', pointsA: 16, pointsB: 5, roundNumber: 2),
  MatchResult(participantA: 'Giansibar', participantB: 'Stibe', pointsA: 8, pointsB: 12, roundNumber: 2),
  MatchResult(participantA: 'Kubbernikus', participantB: 'Meff', pointsA: 8, pointsB: 11, roundNumber: 2),
  MatchResult(participantA: 'Chlötzli Chrigi', participantB: 'Gourmet', pointsA: 12, pointsB: 9, roundNumber: 2),
  MatchResult(participantA: 'Laura', participantB: 'Pitsch Loco', pointsA: 1, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'Cöbi', participantB: 'Eytinu', pointsA: 12, pointsB: 9, roundNumber: 2),
  MatchResult(participantA: 'Schibu', participantB: 'Pluseis', pointsA: 5, pointsB: 16, roundNumber: 2),
  MatchResult(participantA: 'Düpiträn', participantB: 'Kubbacca', pointsA: 9, pointsB: 7, roundNumber: 2),
  // Runde 3
  MatchResult(participantA: 'Buschi', participantB: 'Sparringspartner', pointsA: 8, pointsB: 16, roundNumber: 3),
  MatchResult(participantA: 'Ozempic', participantB: 'Boskoop', pointsA: 12, pointsB: 12, roundNumber: 3),
  MatchResult(participantA: 'Hafenkneipenleiter', participantB: 'Ju', pointsA: 10, pointsB: 11, roundNumber: 3),
  MatchResult(participantA: 'Coco Vin', participantB: 'Voegi18', pointsA: 4, pointsB: 16, roundNumber: 3),
  MatchResult(participantA: 'Beni the Gun', participantB: 'Mandoo', pointsA: 16, pointsB: 5, roundNumber: 3),
  MatchResult(participantA: 'Ikarus', participantB: 'Clint Eastwood', pointsA: 11, pointsB: 9, roundNumber: 3),
  MatchResult(participantA: 'Chopstick', participantB: 'mésé', pointsA: 10, pointsB: 10, roundNumber: 3),
  MatchResult(participantA: 'Hakubba Matata', participantB: 'Adi M', pointsA: 16, pointsB: 5, roundNumber: 3),
  MatchResult(participantA: 'Rolli', participantB: 'Cheneraaal', pointsA: 13, pointsB: 8, roundNumber: 3),
  MatchResult(participantA: 'Kubb-Elch', participantB: 'Backpacker', pointsA: 12, pointsB: 10, roundNumber: 3),
  MatchResult(participantA: 'simuck', participantB: 'Panda', pointsA: 10, pointsB: 12, roundNumber: 3),
  MatchResult(participantA: 'Gravensteiner', participantB: 'KUBBO', pointsA: 9, pointsB: 12, roundNumber: 3),
  MatchResult(participantA: 'joker', participantB: 'Cheesu', pointsA: 16, pointsB: 6, roundNumber: 3),
  MatchResult(participantA: 'Balu der Bär', participantB: 'Galbi', pointsA: 16, pointsB: 6, roundNumber: 3),
  MatchResult(participantA: 'Deadeye Dye', participantB: 'Fül', pointsA: 16, pointsB: 7, roundNumber: 3),
  MatchResult(participantA: 'Croci-Torti', participantB: 'RougeOMat', pointsA: 16, pointsB: 6, roundNumber: 3),
  MatchResult(participantA: 'Stüfi', participantB: "N'Ivo", pointsA: 16, pointsB: 5, roundNumber: 3),
  MatchResult(participantA: 'The Sheep', participantB: 'Driiibiii', pointsA: 3, pointsB: 16, roundNumber: 3),
  MatchResult(participantA: 'Wadli', participantB: 'Pabst', pointsA: 13, pointsB: 12, roundNumber: 3),
  MatchResult(participantA: 'Bradley', participantB: 'Magic Marco', pointsA: 16, pointsB: 5, roundNumber: 3),
  MatchResult(participantA: 'Lúcio', participantB: 'Pitsch Loco', pointsA: 11, pointsB: 8, roundNumber: 3),
  MatchResult(participantA: 'LaMartina', participantB: 'Jim Panse', pointsA: 11, pointsB: 10, roundNumber: 3),
  MatchResult(participantA: 'Chibber', participantB: 'Die Nase', pointsA: 16, pointsB: 1, roundNumber: 3),
  MatchResult(participantA: 'Borgonuovo', participantB: 'Pluseis', pointsA: 11, pointsB: 9, roundNumber: 3),
  MatchResult(participantA: 'Mariiins', participantB: 'Louis de Kubbi', pointsA: 4, pointsB: 16, roundNumber: 3),
  MatchResult(participantA: 'Snoerkel', participantB: 'Chlötzli Chrigi', pointsA: 8, pointsB: 11, roundNumber: 3),
  MatchResult(participantA: 'Börny', participantB: 'Stibe', pointsA: 5, pointsB: 12, roundNumber: 3),
  MatchResult(participantA: 'ND', participantB: 'Meff', pointsA: 11, pointsB: 7, roundNumber: 3),
  MatchResult(participantA: 'Sie', participantB: 'Cöbi', pointsA: 3, pointsB: 16, roundNumber: 3),
  MatchResult(participantA: 'Pischi', participantB: 'Giansibar', pointsA: 11, pointsB: 11, roundNumber: 3),
  MatchResult(participantA: 'Kubbernikus', participantB: 'Gourmet', pointsA: 11, pointsB: 4, roundNumber: 3),
  MatchResult(participantA: 'Persuadé', participantB: 'Benji', pointsA: 7, pointsB: 16, roundNumber: 3),
  MatchResult(participantA: 'Eytinu', participantB: 'All in', pointsA: 11, pointsB: 10, roundNumber: 3),
  MatchResult(participantA: 'Tom Kreuzfahrt', participantB: 'Düpiträn', pointsA: 7, pointsB: 10, roundNumber: 3),
  MatchResult(participantA: 'Sarys', participantB: 'Diese', pointsA: 8, pointsB: 10, roundNumber: 3),
  MatchResult(participantA: 'Kubbacca', participantB: 'Schibu', pointsA: 16, pointsB: 2, roundNumber: 3),
  // Runde 4
  MatchResult(participantA: 'Sparringspartner', participantB: 'Voegi18', pointsA: 12, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'Beni the Gun', participantB: 'Ozempic', pointsA: 12, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'Boskoop', participantB: 'Ju', pointsA: 8, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Hakubba Matata', participantB: 'Hafenkneipenleiter', pointsA: 10, pointsB: 12, roundNumber: 4),
  MatchResult(participantA: 'Buschi', participantB: 'Rolli', pointsA: 16, pointsB: 4, roundNumber: 4),
  MatchResult(participantA: 'Ikarus', participantB: 'Chopstick', pointsA: 12, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'joker', participantB: 'Kubb-Elch', pointsA: 8, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'Balu der Bär', participantB: 'mésé', pointsA: 12, pointsB: 9, roundNumber: 4),
  MatchResult(participantA: 'Clint Eastwood', participantB: 'Panda', pointsA: 16, pointsB: 5, roundNumber: 4),
  MatchResult(participantA: 'Deadeye Dye', participantB: 'Croci-Torti', pointsA: 5, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Stüfi', participantB: 'Coco Vin', pointsA: 7, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Driiibiii', participantB: 'Bradley', pointsA: 16, pointsB: 5, roundNumber: 4),
  MatchResult(participantA: 'Backpacker', participantB: 'Cheneraaal', pointsA: 11, pointsB: 9, roundNumber: 4),
  MatchResult(participantA: 'simuck', participantB: 'KUBBO', pointsA: 5, pointsB: 12, roundNumber: 4),
  MatchResult(participantA: 'Mandoo', participantB: 'Gravensteiner', pointsA: 16, pointsB: 4, roundNumber: 4),
  MatchResult(participantA: 'Chibber', participantB: 'Wadli', pointsA: 7, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Louis de Kubbi', participantB: 'Adi M', pointsA: 8, pointsB: 8, roundNumber: 4),
  MatchResult(participantA: 'Pabst', participantB: 'Lúcio', pointsA: 16, pointsB: 7, roundNumber: 4),
  MatchResult(participantA: 'Cöbi', participantB: 'Borgonuovo', pointsA: 16, pointsB: 6, roundNumber: 4),
  MatchResult(participantA: 'LaMartina', participantB: 'Cheesu', pointsA: 4, pointsB: 13, roundNumber: 4),
  MatchResult(participantA: 'Fül', participantB: 'Galbi', pointsA: 1, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Jim Panse', participantB: 'Stibe', pointsA: 10, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'RougeOMat', participantB: 'Pitsch Loco', pointsA: 12, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'Chlötzli Chrigi', participantB: 'Benji', pointsA: 4, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Pluseis', participantB: "N'Ivo", pointsA: 9, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'ND', participantB: 'Magic Marco', pointsA: 6, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Pischi', participantB: 'Snoerkel', pointsA: 13, pointsB: 9, roundNumber: 4),
  MatchResult(participantA: 'Kubbacca', participantB: 'The Sheep', pointsA: 4, pointsB: 12, roundNumber: 4),
  MatchResult(participantA: 'Giansibar', participantB: 'Kubbernikus', pointsA: 12, pointsB: 9, roundNumber: 4),
  MatchResult(participantA: 'Eytinu', participantB: 'Meff', pointsA: 16, pointsB: 0, roundNumber: 4),
  MatchResult(participantA: 'Mariiins', participantB: 'Börny', pointsA: 10, pointsB: 10, roundNumber: 4),
  MatchResult(participantA: 'All in', participantB: 'Düpiträn', pointsA: 6, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Laura', participantB: 'Diese', pointsA: 10, pointsB: 12, roundNumber: 4),
  MatchResult(participantA: 'Die Nase', participantB: 'Persuadé', pointsA: 4, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Sarys', participantB: 'Sie', pointsA: 4, pointsB: 16, roundNumber: 4),
  MatchResult(participantA: 'Tom Kreuzfahrt', participantB: 'Gourmet', pointsA: 6, pointsB: 16, roundNumber: 4),
  // Runde 5
  MatchResult(participantA: 'Sparringspartner', participantB: 'Ju', pointsA: 11, pointsB: 8, roundNumber: 5),
  MatchResult(participantA: 'Voegi18', participantB: 'Beni the Gun', pointsA: 10, pointsB: 16, roundNumber: 5),
  MatchResult(participantA: 'Buschi', participantB: 'Hafenkneipenleiter', pointsA: 11, pointsB: 10, roundNumber: 5),
  MatchResult(participantA: 'Ozempic', participantB: 'Clint Eastwood', pointsA: 10, pointsB: 12, roundNumber: 5),
  MatchResult(participantA: 'Hakubba Matata', participantB: 'Croci-Torti', pointsA: 7, pointsB: 13, roundNumber: 5),
  MatchResult(participantA: 'Boskoop', participantB: 'Driiibiii', pointsA: 11, pointsB: 8, roundNumber: 5),
  MatchResult(participantA: 'Coco Vin', participantB: 'Ikarus', pointsA: 10, pointsB: 10, roundNumber: 5),
  MatchResult(participantA: 'Balu der Bär', participantB: 'Mandoo', pointsA: 16, pointsB: 6, roundNumber: 5),
  MatchResult(participantA: 'Wadli', participantB: 'Chopstick', pointsA: 4, pointsB: 16, roundNumber: 5),
  MatchResult(participantA: 'Kubb-Elch', participantB: 'Pabst', pointsA: 12, pointsB: 11, roundNumber: 5),
  MatchResult(participantA: 'KUBBO', participantB: 'joker', pointsA: 11, pointsB: 10, roundNumber: 5),
  MatchResult(participantA: 'mésé', participantB: 'Backpacker', pointsA: 9, pointsB: 11, roundNumber: 5),
  MatchResult(participantA: 'Cöbi', participantB: 'Rolli', pointsA: 9, pointsB: 9, roundNumber: 5),
  MatchResult(participantA: 'Stüfi', participantB: 'Galbi', pointsA: 16, pointsB: 1, roundNumber: 5),
  MatchResult(participantA: 'Cheneraaal', participantB: 'Benji', pointsA: 16, pointsB: 6, roundNumber: 5),
  MatchResult(participantA: 'Panda', participantB: 'Deadeye Dye', pointsA: 5, pointsB: 12, roundNumber: 5),
  MatchResult(participantA: 'Cheesu', participantB: 'Bradley', pointsA: 10, pointsB: 11, roundNumber: 5),
  MatchResult(participantA: 'Louis de Kubbi', participantB: 'Chibber', pointsA: 4, pointsB: 16, roundNumber: 5),
  MatchResult(participantA: 'Adi M', participantB: 'Magic Marco', pointsA: 16, pointsB: 5, roundNumber: 5),
  MatchResult(participantA: 'simuck', participantB: 'Gravensteiner', pointsA: 4, pointsB: 16, roundNumber: 5),
  MatchResult(participantA: 'RougeOMat', participantB: 'Jim Panse', pointsA: 12, pointsB: 10, roundNumber: 5),
  MatchResult(participantA: 'Eytinu', participantB: 'Lúcio', pointsA: 8, pointsB: 9, roundNumber: 5),
  MatchResult(participantA: 'Stibe', participantB: 'Pitsch Loco', pointsA: 10, pointsB: 8, roundNumber: 5),
  MatchResult(participantA: 'Pischi', participantB: "N'Ivo", pointsA: 16, pointsB: 6, roundNumber: 5),
  MatchResult(participantA: 'Pluseis', participantB: 'Düpiträn', pointsA: 11, pointsB: 4, roundNumber: 5),
  MatchResult(participantA: 'Borgonuovo', participantB: 'Giansibar', pointsA: 10, pointsB: 11, roundNumber: 5),
  MatchResult(participantA: 'The Sheep', participantB: 'Persuadé', pointsA: 11, pointsB: 7, roundNumber: 5),
  MatchResult(participantA: 'LaMartina', participantB: 'Snoerkel', pointsA: 5, pointsB: 12, roundNumber: 5),
  MatchResult(participantA: 'Sie', participantB: 'Kubbernikus', pointsA: 6, pointsB: 10, roundNumber: 5),
  MatchResult(participantA: 'ND', participantB: 'Gourmet', pointsA: 7, pointsB: 16, roundNumber: 5),
  MatchResult(participantA: 'Chlötzli Chrigi', participantB: 'Diese', pointsA: 2, pointsB: 16, roundNumber: 5),
  MatchResult(participantA: 'Mariiins', participantB: 'Laura', pointsA: 11, pointsB: 10, roundNumber: 5),
  MatchResult(participantA: 'Börny', participantB: 'Fül', pointsA: 11, pointsB: 9, roundNumber: 5),
  MatchResult(participantA: 'Kubbacca', participantB: 'All in', pointsA: 5, pointsB: 4, roundNumber: 5),
  MatchResult(participantA: 'Schibu', participantB: 'Die Nase', pointsA: 10, pointsB: 5, roundNumber: 5),
  MatchResult(participantA: 'Tom Kreuzfahrt', participantB: 'Sarys', pointsA: 5, pointsB: 16, roundNumber: 5),
  // Runde 6
  MatchResult(participantA: 'Beni the Gun', participantB: 'Sparringspartner', pointsA: 11, pointsB: 11, roundNumber: 6),
  MatchResult(participantA: 'Voegi18', participantB: 'Ju', pointsA: 6, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'Buschi', participantB: 'Croci-Torti', pointsA: 16, pointsB: 8, roundNumber: 6),
  MatchResult(participantA: 'Balu der Bär', participantB: 'Clint Eastwood', pointsA: 5, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'Hafenkneipenleiter', participantB: 'Ozempic', pointsA: 10, pointsB: 13, roundNumber: 6),
  MatchResult(participantA: 'Chopstick', participantB: 'Boskoop', pointsA: 9, pointsB: 11, roundNumber: 6),
  MatchResult(participantA: 'Coco Vin', participantB: 'Hakubba Matata', pointsA: 13, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Ikarus', participantB: 'Driiibiii', pointsA: 16, pointsB: 4, roundNumber: 6),
  MatchResult(participantA: 'Kubb-Elch', participantB: 'Stüfi', pointsA: 16, pointsB: 5, roundNumber: 6),
  MatchResult(participantA: 'Cheneraaal', participantB: 'Pabst', pointsA: 5, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'KUBBO', participantB: 'Backpacker', pointsA: 9, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Chibber', participantB: 'Mandoo', pointsA: 11, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'joker', participantB: 'Adi M', pointsA: 16, pointsB: 9, roundNumber: 6),
  MatchResult(participantA: 'mésé', participantB: 'Cöbi', pointsA: 16, pointsB: 6, roundNumber: 6),
  MatchResult(participantA: 'Deadeye Dye', participantB: 'Gravensteiner', pointsA: 12, pointsB: 8, roundNumber: 6),
  MatchResult(participantA: 'Rolli', participantB: 'Wadli', pointsA: 12, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Pischi', participantB: 'Bradley', pointsA: 16, pointsB: 1, roundNumber: 6),
  MatchResult(participantA: 'Cheesu', participantB: 'RougeOMat', pointsA: 12, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Benji', participantB: 'Jim Panse', pointsA: 4, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'Stibe', participantB: 'Gourmet', pointsA: 9, pointsB: 8, roundNumber: 6),
  MatchResult(participantA: 'Panda', participantB: 'Pluseis', pointsA: 9, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Diese', participantB: 'Lúcio', pointsA: 13, pointsB: 9, roundNumber: 6),
  MatchResult(participantA: 'Giansibar', participantB: 'The Sheep', pointsA: 5, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'Eytinu', participantB: 'Galbi', pointsA: 11, pointsB: 11, roundNumber: 6),
  MatchResult(participantA: 'Louis de Kubbi', participantB: 'Magic Marco', pointsA: 7, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'Borgonuovo', participantB: 'Pitsch Loco', pointsA: 16, pointsB: 4, roundNumber: 6),
  MatchResult(participantA: 'Snoerkel', participantB: 'simuck', pointsA: 11, pointsB: 4, roundNumber: 6),
  MatchResult(participantA: "N'Ivo", participantB: 'Kubbernikus', pointsA: 2, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Persuadé', participantB: 'Mariiins', pointsA: 8, pointsB: 4, roundNumber: 6),
  MatchResult(participantA: 'Börny', participantB: 'Düpiträn', pointsA: 9, pointsB: 6, roundNumber: 6),
  MatchResult(participantA: 'Laura', participantB: 'ND', pointsA: 8, pointsB: 10, roundNumber: 6),
  MatchResult(participantA: 'Sie', participantB: 'Fül', pointsA: 4, pointsB: 4, roundNumber: 6),
  MatchResult(participantA: 'LaMartina', participantB: 'Sarys', pointsA: 3, pointsB: 16, roundNumber: 6),
  MatchResult(participantA: 'Meff', participantB: 'Schibu', pointsA: 16, pointsB: 5, roundNumber: 6),
  MatchResult(participantA: 'Chlötzli Chrigi', participantB: 'Kubbacca', pointsA: 16, pointsB: 2, roundNumber: 6),
  MatchResult(participantA: 'All in', participantB: 'Die Nase', pointsA: 8, pointsB: 9, roundNumber: 6),
  // Runde 7
  MatchResult(participantA: 'Beni the Gun', participantB: 'Ju', pointsA: 16, pointsB: 7, roundNumber: 7),
  MatchResult(participantA: 'Buschi', participantB: 'Clint Eastwood', pointsA: 11, pointsB: 10, roundNumber: 7),
  MatchResult(participantA: 'Sparringspartner', participantB: 'Ozempic', pointsA: 11, pointsB: 12, roundNumber: 7),
  MatchResult(participantA: 'Ikarus', participantB: 'Kubb-Elch', pointsA: 12, pointsB: 8, roundNumber: 7),
  MatchResult(participantA: 'Coco Vin', participantB: 'Pabst', pointsA: 12, pointsB: 10, roundNumber: 7),
  MatchResult(participantA: 'Hafenkneipenleiter', participantB: 'Voegi18', pointsA: 5, pointsB: 16, roundNumber: 7),
  MatchResult(participantA: 'Boskoop', participantB: 'Croci-Torti', pointsA: 11, pointsB: 11, roundNumber: 7),
  MatchResult(participantA: 'Chopstick', participantB: 'joker', pointsA: 16, pointsB: 2, roundNumber: 7),
  MatchResult(participantA: 'Balu der Bär', participantB: 'Hakubba Matata', pointsA: 8, pointsB: 16, roundNumber: 7),
  MatchResult(participantA: 'mésé', participantB: 'Pischi', pointsA: 16, pointsB: 3, roundNumber: 7),
  MatchResult(participantA: 'Chibber', participantB: 'Backpacker', pointsA: 6, pointsB: 16, roundNumber: 7),
  MatchResult(participantA: 'KUBBO', participantB: 'Mandoo', pointsA: 16, pointsB: 7, roundNumber: 7),
  MatchResult(participantA: 'Deadeye Dye', participantB: 'Rolli', pointsA: 9, pointsB: 12, roundNumber: 7),
  MatchResult(participantA: 'Cheneraaal', participantB: 'Adi M', pointsA: 10, pointsB: 11, roundNumber: 7),
  MatchResult(participantA: 'Stüfi', participantB: 'Driiibiii', pointsA: 4, pointsB: 16, roundNumber: 7),
  MatchResult(participantA: 'Jim Panse', participantB: 'Wadli', pointsA: 12, pointsB: 10, roundNumber: 7),
  MatchResult(participantA: 'Cheesu', participantB: 'Gravensteiner', pointsA: 13, pointsB: 12, roundNumber: 7),
  MatchResult(participantA: 'The Sheep', participantB: 'Cöbi', pointsA: 8, pointsB: 12, roundNumber: 7),
  MatchResult(participantA: 'RougeOMat', participantB: 'Magic Marco', pointsA: 12, pointsB: 9, roundNumber: 7),
  MatchResult(participantA: 'Borgonuovo', participantB: 'Diese', pointsA: 16, pointsB: 4, roundNumber: 7),
  MatchResult(participantA: 'Stibe', participantB: 'Pluseis', pointsA: 16, pointsB: 4, roundNumber: 7),
  MatchResult(participantA: 'Eytinu', participantB: 'Panda', pointsA: 9, pointsB: 11, roundNumber: 7),
  MatchResult(participantA: 'Galbi', participantB: 'Snoerkel', pointsA: 10, pointsB: 5, roundNumber: 7),
  MatchResult(participantA: 'Gourmet', participantB: 'Lúcio', pointsA: 7, pointsB: 12, roundNumber: 7),
  MatchResult(participantA: 'Sarys', participantB: 'Meff', pointsA: 13, pointsB: 8, roundNumber: 7),
  MatchResult(participantA: 'Bradley', participantB: 'Benji', pointsA: 2, pointsB: 16, roundNumber: 7),
  MatchResult(participantA: 'Louis de Kubbi', participantB: 'Kubbernikus', pointsA: 4, pointsB: 5, roundNumber: 7),
  MatchResult(participantA: 'Giansibar', participantB: 'Börny', pointsA: 16, pointsB: 3, roundNumber: 7),
  MatchResult(participantA: 'Persuadé', participantB: 'Pitsch Loco', pointsA: 8, pointsB: 4, roundNumber: 7),
  MatchResult(participantA: 'Chlötzli Chrigi', participantB: 'ND', pointsA: 9, pointsB: 8, roundNumber: 7),
  MatchResult(participantA: 'simuck', participantB: 'Laura', pointsA: 13, pointsB: 5, roundNumber: 7),
  MatchResult(participantA: 'Düpiträn', participantB: 'Mariiins', pointsA: 5, pointsB: 16, roundNumber: 7),
  MatchResult(participantA: "N'Ivo", participantB: 'Sie', pointsA: 10, pointsB: 7, roundNumber: 7),
  MatchResult(participantA: 'Tom Kreuzfahrt', participantB: 'Fül', pointsA: 12, pointsB: 6, roundNumber: 7),
  MatchResult(participantA: 'LaMartina', participantB: 'Die Nase', pointsA: 4, pointsB: 3, roundNumber: 7),
  MatchResult(participantA: 'Schibu', participantB: 'All in', pointsA: 1, pointsB: 16, roundNumber: 7),
  // Runde 8
  MatchResult(participantA: 'Beni the Gun', participantB: 'Buschi', pointsA: 9, pointsB: 16, roundNumber: 8),
  MatchResult(participantA: 'Sparringspartner', participantB: 'Clint Eastwood', pointsA: 9, pointsB: 9, roundNumber: 8),
  MatchResult(participantA: 'Ju', participantB: 'Ikarus', pointsA: 13, pointsB: 12, roundNumber: 8),
  MatchResult(participantA: 'Voegi18', participantB: 'Ozempic', pointsA: 16, pointsB: 6, roundNumber: 8),
  MatchResult(participantA: 'Chopstick', participantB: 'Coco Vin', pointsA: 16, pointsB: 6, roundNumber: 8),
  MatchResult(participantA: 'mésé', participantB: 'Hakubba Matata', pointsA: 13, pointsB: 11, roundNumber: 8),
  MatchResult(participantA: 'Boskoop', participantB: 'Pabst', pointsA: 9, pointsB: 12, roundNumber: 8),
  MatchResult(participantA: 'Croci-Torti', participantB: 'Kubb-Elch', pointsA: 12, pointsB: 8, roundNumber: 8),
  MatchResult(participantA: 'Backpacker', participantB: 'Driiibiii', pointsA: 16, pointsB: 6, roundNumber: 8),
  MatchResult(participantA: 'KUBBO', participantB: 'Hafenkneipenleiter', pointsA: 7, pointsB: 16, roundNumber: 8),
  MatchResult(participantA: 'Balu der Bär', participantB: 'Rolli', pointsA: 5, pointsB: 16, roundNumber: 8),
  MatchResult(participantA: 'Borgonuovo', participantB: 'Adi M', pointsA: 10, pointsB: 9, roundNumber: 8),
  MatchResult(participantA: 'Cheesu', participantB: 'Jim Panse', pointsA: 16, pointsB: 5, roundNumber: 8),
  MatchResult(participantA: 'Cheneraaal', participantB: 'Deadeye Dye', pointsA: 10, pointsB: 11, roundNumber: 8),
  MatchResult(participantA: 'joker', participantB: 'Mandoo', pointsA: 4, pointsB: 16, roundNumber: 8),
  MatchResult(participantA: 'Gravensteiner', participantB: 'Chibber', pointsA: 16, pointsB: 3, roundNumber: 8),
  MatchResult(participantA: 'Wadli', participantB: 'Cöbi', pointsA: 11, pointsB: 10, roundNumber: 8),
  MatchResult(participantA: 'RougeOMat', participantB: 'Stibe', pointsA: 16, pointsB: 7, roundNumber: 8),
  MatchResult(participantA: 'Pischi', participantB: 'The Sheep', pointsA: 4, pointsB: 16, roundNumber: 8),
  MatchResult(participantA: 'Magic Marco', participantB: 'Stüfi', pointsA: 10, pointsB: 10, roundNumber: 8),
  MatchResult(participantA: 'Benji', participantB: 'Panda', pointsA: 16, pointsB: 6, roundNumber: 8),
  MatchResult(participantA: 'Giansibar', participantB: 'Lúcio', pointsA: 9, pointsB: 9, roundNumber: 8),
  MatchResult(participantA: 'Sarys', participantB: 'Eytinu', pointsA: 4, pointsB: 16, roundNumber: 8),
  MatchResult(participantA: 'Galbi', participantB: 'Diese', pointsA: 10, pointsB: 11, roundNumber: 8),
  MatchResult(participantA: 'Gourmet', participantB: 'Mariiins', pointsA: 10, pointsB: 8, roundNumber: 8),
  MatchResult(participantA: 'Meff', participantB: 'simuck', pointsA: 9, pointsB: 12, roundNumber: 8),
  MatchResult(participantA: 'Snoerkel', participantB: 'Pluseis', pointsA: 11, pointsB: 6, roundNumber: 8),
  MatchResult(participantA: 'Chlötzli Chrigi', participantB: 'Persuadé', pointsA: 16, pointsB: 2, roundNumber: 8),
  MatchResult(participantA: 'Kubbernikus', participantB: 'ND', pointsA: 12, pointsB: 8, roundNumber: 8),
  MatchResult(participantA: 'Louis de Kubbi', participantB: 'Tom Kreuzfahrt', pointsA: 10, pointsB: 5, roundNumber: 8),
  MatchResult(participantA: 'Bradley', participantB: "N'Ivo", pointsA: 8, pointsB: 10, roundNumber: 8),
  MatchResult(participantA: 'All in', participantB: 'Börny', pointsA: 8, pointsB: 10, roundNumber: 8),
  MatchResult(participantA: 'Pitsch Loco', participantB: 'Düpiträn', pointsA: 11, pointsB: 8, roundNumber: 8),
  MatchResult(participantA: 'Laura', participantB: 'Kubbacca', pointsA: 4, pointsB: 4, roundNumber: 8),
  MatchResult(participantA: 'Sie', participantB: 'Schibu', pointsA: 16, pointsB: 5, roundNumber: 8),
  MatchResult(participantA: 'Fül', participantB: 'Die Nase', pointsA: 5, pointsB: 4, roundNumber: 8),
  // Freilose (Schoch: 16 Punkte für den Freilos-Spieler)
  MatchResult(participantA: 'Die Nase', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 1),
  MatchResult(participantA: 'Börny', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 2),
  MatchResult(participantA: 'Laura', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 3),
  MatchResult(participantA: 'Schibu', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 4),
  MatchResult(participantA: 'Meff', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 5),
  MatchResult(participantA: 'Tom Kreuzfahrt', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 6),
  MatchResult(participantA: 'Kubbacca', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 7),
  MatchResult(participantA: 'LaMartina', participantB: null, pointsA: 16, pointsB: 0, roundNumber: 8),
];

/// All 73 participants (kubb.live ranking order).
const smEinzel2026Participants = <String>[
  'Buschi',
  'Beni the Gun',
  'Voegi18',
  'Chopstick',
  'Ju',
  'Sparringspartner',
  'Ikarus',
  'Clint Eastwood',
  'mésé',
  'Backpacker',
  'Croci-Torti',
  'Hakubba Matata',
  'Pabst',
  'Hafenkneipenleiter',
  'Ozempic',
  'Boskoop',
  'Coco Vin',
  'Rolli',
  'Kubb-Elch',
  'Cheesu',
  'Gravensteiner',
  'KUBBO',
  'Mandoo',
  'RougeOMat',
  'Borgonuovo',
  'Driiibiii',
  'Deadeye Dye',
  'The Sheep',
  'Cheneraaal',
  'Adi M',
  'Benji',
  'Balu der Bär',
  'Wadli',
  'Cöbi',
  'Eytinu',
  'Jim Panse',
  'Magic Marco',
  'Stibe',
  'Stüfi',
  'joker',
  'Chibber',
  'Giansibar',
  'Lúcio',
  'Pischi',
  'Galbi',
  'Diese',
  'Chlötzli Chrigi',
  'Panda',
  'simuck',
  'Gourmet',
  'Snoerkel',
  'Sarys',
  'Meff',
  'Mariiins',
  'Kubbernikus',
  'Pluseis',
  'Louis de Kubbi',
  'Sie',
  'ND',
  'Pitsch Loco',
  "N'Ivo",
  'Börny',
  'Bradley',
  'All in',
  'LaMartina',
  'Tom Kreuzfahrt',
  'Persuadé',
  'Düpiträn',
  'Laura',
  'Kubbacca',
  'Fül',
  'Schibu',
  'Die Nase',
];

/// Expected total points per player (own scores summed, bye = 16).
const smEinzel2026ExpectedPoints = <String, int>{
  'Buschi': 110,
  'Beni the Gun': 109,
  'Voegi18': 106,
  'Chopstick': 105,
  'Ju': 103,
  'Sparringspartner': 102,
  'Ikarus': 101,
  'Clint Eastwood': 100,
  'mésé': 100,
  'Backpacker': 99,
  'Croci-Torti': 97,
  'Hakubba Matata': 97,
  'Pabst': 97,
  'Hafenkneipenleiter': 95,
  'Ozempic': 95,
  'Boskoop': 94,
  'Coco Vin': 93,
  'Rolli': 93,
  'Kubb-Elch': 92,
  'Cheesu': 92,
  'Gravensteiner': 90,
  'KUBBO': 90,
  'Mandoo': 89,
  'RougeOMat': 89,
  'Borgonuovo': 87,
  'Driiibiii': 86,
  'Deadeye Dye': 86,
  'The Sheep': 86,
  'Cheneraaal': 85,
  'Adi M': 85,
  'Benji': 85,
  'Balu der Bär': 84,
  'Wadli': 84,
  'Cöbi': 83,
  'Eytinu': 82,
  'Jim Panse': 81,
  'Magic Marco': 80,
  'Stibe': 80,
  'Stüfi': 79,
  'joker': 78,
  'Chibber': 77,
  'Giansibar': 76,
  'Lúcio': 76,
  'Pischi': 76,
  'Galbi': 76,
  'Diese': 75,
  'Chlötzli Chrigi': 74,
  'Panda': 73,
  'simuck': 73,
  'Gourmet': 73,
  'Snoerkel': 72,
  'Sarys': 71,
  'Meff': 71,
  'Mariiins': 70,
  'Kubbernikus': 69,
  'Pluseis': 67,
  'Louis de Kubbi': 66,
  'Sie': 66,
  'ND': 65,
  'Pitsch Loco': 64,
  "N'Ivo": 64,
  'Börny': 64,
  'Bradley': 63,
  'All in': 62,
  'LaMartina': 61,
  'Tom Kreuzfahrt': 61,
  'Persuadé': 60,
  'Düpiträn': 59,
  'Laura': 57,
  'Kubbacca': 55,
  'Fül': 53,
  'Schibu': 46,
  'Die Nase': 44,
};

/// Expected Buchholz per player (schoch-swiss spec §5, kubb.live).
/// Explicitly NOT the naive opponent-total sum (Buschi naive = 746).
const smEinzel2026ExpectedBuchholz = <String, int>{
  'Buschi': 682,
  'Beni the Gun': 691,
  'Voegi18': 650,
  'Chopstick': 666,
  'Ju': 688,
  'Sparringspartner': 720,
  'Ikarus': 674,
  'Clint Eastwood': 658,
  'mésé': 628,
  'Backpacker': 612,
  'Croci-Torti': 659,
  'Hakubba Matata': 637,
  'Pabst': 617,
  'Hafenkneipenleiter': 678,
  'Ozempic': 678,
  'Boskoop': 664,
  'Coco Vin': 650,
  'Rolli': 637,
  'Kubb-Elch': 631,
  'Cheesu': 576,
  'Gravensteiner': 592,
  'KUBBO': 575,
  'Mandoo': 594,
  'RougeOMat': 577,
  'Borgonuovo': 537,
  'Driiibiii': 641,
  'Deadeye Dye': 584,
  'The Sheep': 533,
  'Cheneraaal': 613,
  'Adi M': 588,
  'Benji': 534,
  'Balu der Bär': 640,
  'Wadli': 600,
  'Cöbi': 600,
  'Eytinu': 525,
  'Jim Panse': 563,
  'Magic Marco': 538,
  'Stibe': 531,
  'Stüfi': 570,
  'joker': 642,
  'Chibber': 552,
  'Giansibar': 555,
  'Lúcio': 535,
  'Pischi': 535,
  'Galbi': 527,
  'Diese': 524,
  'Chlötzli Chrigi': 503,
  'Panda': 575,
  'simuck': 521,
  'Gourmet': 499,
  'Snoerkel': 512,
  'Sarys': 493,
  'Meff': 411,
  'Mariiins': 423,
  'Kubbernikus': 513,
  'Pluseis': 485,
  'Louis de Kubbi': 541,
  'Sie': 445,
  'ND': 490,
  'Pitsch Loco': 536,
  "N'Ivo": 518,
  'Börny': 415,
  'Bradley': 565,
  'All in': 438,
  'LaMartina': 426,
  'Tom Kreuzfahrt': 399,
  'Persuadé': 500,
  'Düpiträn': 460,
  'Laura': 405,
  'Kubbacca': 405,
  'Fül': 483,
  'Schibu': 353,
  'Die Nase': 390,
};
